// crossPlatformProgramming/Lab1-3/src/components/Header/header.tsx
import { IonHeader, IonToolbar, IonTitle, IonText } from "@ionic/react";
import React from "react";

const Header = () => {
   return (
      <IonHeader>
         <IonToolbar>
            <IonTitle>
               <IonText color="white">
                  <h1>Кошулько Ярослав</h1>
                  <h3>Група: КН-31 | Варіант №15</h3>
               </IonText>
            </IonTitle>
         </IonToolbar>
      </IonHeader>
   );
};

export default Header;

// crossPlatformProgramming/Lab5/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { IonicModule } from '@ionic/angular';

@Component({
  selector: 'app-header',
  standalone: true,
  templateUrl: './header.component.html',
  //   styleUrls: ['./header.component.css'],
  imports: [IonicModule],
})
export class HeaderComponent {}

<ion-header>
  <ion-toolbar>
    <ion-title>
      <ion-text color="white">
        <h1>Кошулько Ярослав</h1>
        <h3>Група: КН-31 | Варіант №15</h3>
      </ion-text>
    </ion-title>
  </ion-toolbar>
</ion-header>
